name: publish
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      # Save key store file.
      - run: echo -n ${{ secrets.TAV_KEY_STORE_FILE }} | base64 -d > ~/try_android_view.jks
      # Make release build and upload to DeployGate
      - run: ./gradlew uploadDeployGateRelease
        env:
          TAV_STORE_PASSWORD: ${{ secrets.TAV_STORE_PASSWORD }}
          TAV_KEY_PASSWORD: ${{ secrets.TAV_KEY_PASSWORD }}
          DEPLOYGATE_APP_OWNER_NAME: ${{ secrets.DEPLOYGATE_APP_OWNER_NAME }}
          DEPLOYGATE_API_TOKEN: ${{ secrets.DEPLOYGATE_API_TOKEN }}
          DEPLOYGATE_DISTRIBUTION_KEY: ${{ secrets.DEPLOYGATE_DISTRIBUTION_KEY }}
